# Generated by Django 4.1.4 on 2022-12-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='base.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='base.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_marriage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_of_death',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='siblings',
            field=models.ManyToManyField(blank=True, related_name='siblings', to='base.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='spouses',
            field=models.ManyToManyField(blank=True, related_name='spouses', to='base.person'),
        ),
    ]
