# Generated by Django 4.1.4 on 2022-12-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_person_parents_alter_person_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='siblings',
            field=models.ManyToManyField(blank=True, related_name='rel_siblings', to='base.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='spouses',
            field=models.ManyToManyField(blank=True, related_name='rel_spouses', to='base.person'),
        ),
    ]
