# Generated by Django 4.1.4 on 2022-12-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_person_siblings_alter_person_spouses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='rel_parents', to='base.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='rel_children', to='base.person'),
        ),
    ]
