# Generated by Django 4.1.4 on 2022-12-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_person_children_alter_person_parents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Member',
        ),
    ]
