# Generated by Django 4.1.4 on 2022-12-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_person_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='rel_parents', to='base.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, related_name='rel_children', to='base.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='siblings',
            field=models.ManyToManyField(blank=True, null=True, related_name='rel_siblings', to='base.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='spouses',
            field=models.ManyToManyField(blank=True, null=True, related_name='rel_spouses', to='base.member'),
        ),
    ]
