# Generated by Django 4.1.4 on 2022-12-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_member_children_alter_member_parents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nee_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
