# Generated by Django 4.1.4 on 2022-12-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_member_nee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nee_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='spouses',
            field=models.ManyToManyField(blank=True, related_name='rel_spouses', to='base.member'),
        ),
    ]
