# Generated by Django 4.1.4 on 2022-12-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_member_nee_name_alter_member_spouses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='rel_parents', to='base.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='rel_children', to='base.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='siblings',
            field=models.ManyToManyField(blank=True, related_name='rel_siblings', to='base.member'),
        ),
    ]
