# Generated by Django 4.1.4 on 2022-12-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_member_children_alter_member_parents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='base.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='base.member'),
        ),
    ]
