# Generated by Django 4.1.4 on 2022-12-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_member_children_alter_member_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='siblings',
            field=models.ManyToManyField(blank=True, to='base.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='spouses',
            field=models.ManyToManyField(blank=True, to='base.member'),
        ),
    ]
