# Generated by Django 4.1.4 on 2022-12-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_member_siblings_alter_member_spouses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='children',
        ),
        migrations.RemoveField(
            model_name='member',
            name='parents',
        ),
    ]
