# Generated by Django 4.1.4 on 2022-12-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_member_children_remove_member_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.member'),
        ),
    ]
